name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Run build script
      run: cmd /c build.bat